CREATE TABLE IF NOT EXISTS sensor_data (
    id SERIAL PRIMARY KEY,
    sensor VARCHAR(50) NOT NULL,
    value DOUBLE PRECISION NOT NULL,
    ts TIMESTAMP WITH TIME ZONE NOT NULL,
    ts_ingest TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);