CREATE TABLE IF NOT EXISTS telemetry (
    -- Unique identifier for the physical or logical device
    device_id UUID NOT NULL,
    -- Reference to the type of measurement (e.g., 1 for Temp, 2 for Humidity)
    metric_id INTEGER NOT NULL,
    -- Original timestamp generated by the device at the moment of measurement
    ts TIMESTAMPTZ NOT NULL,
    -- Numerical measurement value (supports integers and decimals)
    value DOUBLE PRECISION,
    -- Server-side timestamp recording exactly when the record was persisted
    ts_ingest TIMESTAMPTZ DEFAULT NOW(),   
    -- Composite PK: Prevents duplicates and clusters data by device and time
    PRIMARY KEY (device_id, metric_id, ts)
);
-- Index to optimize cleanup jobs and ingestion-based audit queries
CREATE INDEX idx_telemetry_ingest ON telemetry (ts_ingest);